In [1]:
import pandas as pd
import numpy as np
veh_data=pd.read_csv("C:\\Users\\aruna\\Desktop\\ML_vehicle_price_detection\\auto.txt",na_values="?")
veh_data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000.0,19,26,16500.0
3,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102.0,5500.0,24,30,13950.0
4,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500.0,18,22,17450.0

In [2]:
veh_data.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [3]:
# remove the unwanted columns
veh_data=veh_data.drop("normalized-losses",axis=1)
veh_data.head(2)

,symboling,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,13495.0
1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,...,130,mpfi,3.47,2.68,9.0,111.0,5000.0,21,27,16500.0

In [4]:
veh_data.columns

Index(['symboling', 'make', 'fuel-type', 'aspiration', 'num-of-doors',
       'body-style', 'drive-wheels', 'engine-location', 'wheel-base', 'length',
       'width', 'height', 'curb-weight', 'engine-type', 'num-of-cylinders',
       'engine-size', 'fuel-system', 'bore', 'stroke', 'compression-ratio',
       'horsepower', 'peak-rpm', 'city-mpg', 'highway-mpg', 'price'],
      dtype='object')

In [5]:
#  checking for the columns data type and converting into the int/float
veh_data["price"].describe()

count      201.000000
mean     13207.129353
std       7947.066342
min       5118.000000
25%       7775.000000
50%      10295.000000
75%      16500.000000
max      45400.000000
Name: price, dtype: float64

In [6]:
mak={'alfa-romero':1, 'audi':2, 'bmw':3, 'chevrolet':4, 'dodge':5, 'honda':6,'isuzu':7, 'jaguar':8, 'mazda':9, 'mercedes-benz':10, 'mercury':11,
       'mitsubishi':12, 'nissan':13, 'peugot':14, 'plymouth':15, 'porsche':16, 'renault':17,
       'saab':18, 'subaru':19, 'toyota':20, 'volkswagen':21, 'volvo':22}
veh_data["make"].replace(mak,inplace=True)

fueltype={'gas':1, 'diesel':2}
veh_data["fuel-type"].replace(fueltype,inplace=True)

aspirati={'std':1, 'turbo':2}
veh_data["aspiration"].replace(aspirati,inplace=True)

numofdoors={'two':2, 'four':4}
veh_data["num-of-doors"].replace(numofdoors,inplace=True)

bodystyle={'convertible':1, 'hatchback':2 ,'sedan':3, 'wagon':4, 'hardtop':5}
veh_data["body-style"].replace(bodystyle,inplace=True)

drivewheels={'rwd':1, 'fwd':2, '4wd':3}
veh_data["drive-wheels"].replace(drivewheels,inplace=True)

enginelocation={'front':1, 'rear':2}
veh_data["engine-location"].replace(enginelocation,inplace=True)

enginetype={'dohc':1, 'ohcv':2, 'ohc':3, 'l':4, 'rotor':5, 'ohcf':6, 'dohcv':7}
veh_data["engine-type"].replace(enginetype,inplace=True)

numofcylinders={'four':4, 'six':6, 'five':5, 'three':3, 'twelve':12, 'two':2, 'eight':8}
veh_data["num-of-cylinders"].replace(numofcylinders,inplace=True)

fuelsystem={'mpfi':1, '2bbl':2, 'mfi':3, '1bbl':4, 'spfi':5, '4bbl':6, 'idi':7, 'spdi':8}
veh_data["fuel-system"].replace(fuelsystem,inplace=True)

C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["make"].replace(mak,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:4: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["make"].replace(mak,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["fuel-type"].replace(fueltype,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:7: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["fuel-type"].replace(fueltype,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:10: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["aspiration"].replace(aspirati,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:10: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["aspiration"].replace(aspirati,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["num-of-doors"].replace(numofdoors,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:13: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["num-of-doors"].replace(numofdoors,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:16: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["body-style"].replace(bodystyle,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:16: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["body-style"].replace(bodystyle,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["drive-wheels"].replace(drivewheels,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:19: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["drive-wheels"].replace(drivewheels,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:22: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["engine-location"].replace(enginelocation,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:22: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["engine-location"].replace(enginelocation,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:25: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["engine-type"].replace(enginetype,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:25: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["engine-type"].replace(enginetype,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:28: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["num-of-cylinders"].replace(numofcylinders,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["num-of-cylinders"].replace(numofcylinders,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:31: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  veh_data["fuel-system"].replace(fuelsystem,inplace=True)
C:\Users\aruna\AppData\Local\Temp\ipykernel_25408\492446347.py:31: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  veh_data["fuel-system"].replace(fuelsystem,inplace=True)

In [7]:
veh_data.isnull().sum()

symboling            0
make                 0
fuel-type            0
aspiration           0
num-of-doors         2
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 4
stroke               4
compression-ratio    0
horsepower           2
peak-rpm             2
city-mpg             0
highway-mpg          0
price                4
dtype: int64

In [8]:
# from sklearn.impute import SimpleImputer
# fill_nan=SimpleImputer(missing_values=np.nan,strategy="mean")
# num_cols = ['bore', 'stroke', 'horsepower', 'peak-rpm', 'price','num-of-doors']
# veh_data[num_cols] =fill_nan.fit_transform(veh_data[num_cols])
veh_data=veh_data.dropna()

In [9]:
veh_data.isnull().sum()

symboling            0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [10]:
# ## create the traing and testing data set

In [11]:
# ### drop the cloums that are the values are less then the coefficent 
veh_data=veh_data.drop("city-mpg",axis=1)
veh_data=veh_data.drop("peak-rpm",axis=1)
veh_data=veh_data.drop("horsepower",axis=1)
veh_data=veh_data.drop("curb-weight",axis=1)

In [12]:
from sklearn.model_selection import train_test_split
x=veh_data.drop("price",axis=1)
y=veh_data["price"]
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=0)

In [13]:
from sklearn.linear_model import LinearRegression
liner_model=LinearRegression()
liner_model.fit(xtrain,ytrain)

LinearRegression()

In [14]:
# check the accuracy of the training set
liner_model.score(xtrain,ytrain)

0.8979886130711062

In [15]:
# Check for the accuracy of the testing 
liner_model.score(xtest,ytest)

0.8073684019152115

In [16]:
# liner_model.coef_

In [17]:
predictor=xtrain.columns
coef=pd.Series(liner_model.coef_,predictor).sort_values()
print(coef)

fuel-type           -10235.463217
stroke               -3428.371079
drive-wheels         -1580.459565
bore                 -1081.343064
body-style            -360.578422
symboling             -266.766060
make                  -229.051797
fuel-system           -177.548859
wheel-base            -142.382607
num-of-doors          -128.753616
length                  39.811543
highway-mpg             78.552036
engine-size            137.790008
engine-type            153.180886
num-of-cylinders       334.889882
height                 446.459448
compression-ratio      735.604398
width                  891.627442
aspiration            3967.745571
engine-location      11947.881778
dtype: float64

In [18]:
# #### test the algorithms
import math
y_predict=liner_model.predict(xtest)
# print(y_predict)
# find  the mean square error
from sklearn.metrics import mean_squared_error
liner_model_mse=mean_squared_error(y_predict,ytest)
print("liner model_mse is ",math.sqrt(liner_model_mse))

liner model_mse is  3329.691195092254

## second algorithm

In [19]:
from sklearn.linear_model import Lasso
lasso_model=Lasso(alpha=0.5)
lasso_model.fit(xtrain,ytrain)

C:\Users\aruna\AppData\Roaming\Python\Python313\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.293e+06, tolerance: 1.030e+06
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.5)

In [20]:
# check for the training accuracy
lasso_model.score(xtrain,ytrain)

0.8979818319107161

In [21]:
# checking for the testing accuracy
lasso_model.score(xtest,ytest)

0.8096535022607537

In [22]:
y_predict=lasso_model.predict(xtest)
lasso_model_mse=mean_squared_error(y_predict,ytest)
print("the square accuacy is ",math.sqrt(lasso_model_mse))

the square accuacy is  3309.8829757248786

### third algorithm

In [23]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=0.2)
ridge_model.fit(xtrain,ytrain)

Ridge(alpha=0.2)

In [24]:
#### traing accuracy
ridge_model.score(xtrain,ytrain)

0.8971845035091599

In [25]:
#### testig accuracy 
ridge_model.score(xtest,ytest)

0.8176355316911751

In [26]:
y_predict=ridge_model.predict(xtest)
# score=ridge_model
ridge_model_mse=mean_squared_error(y_predict,ytest)
print(" the mean square value is ",math.sqrt(ridge_model_mse))

 the mean square value is  3239.741106014137

In [27]:
# import pandas as pd

# 1. Input vehicle data (already encoded)
new_car_data = {
    'symboling': 3,
    'make': 10,
    'fuel-type': 1,
    'aspiration': 1,
    'num-of-doors': 4,
    'body-style': 2,
    'drive-wheels': 2,
    'engine-location': 1,
    'wheel-base': 99.8,
    'length': 176.6,
    'width': 66.2,
    'height': 54.3,
    'engine-type': 2,
    'num-of-cylinders': 4,
    'engine-size': 109,
    'fuel-system': 1,
    'bore': 3.19,
    'stroke': 3.40,
    'compression-ratio': 10.0,
    'highway-mpg': 15
}

# 2. Convert to DataFrame
df_new = pd.DataFrame([new_car_data])

# 3. Ensure column order matches training data
df_new = df_new[xtrain.columns]

# 4. Predict
predicted_price = ridge_model.predict(df_new)

print(f"The predicted price for this vehicle is: ${predicted_price[0]:.2f}")

The predicted price for this vehicle is: $8920.28

In [28]:
import pickle

# Save the model
with open('ridge_model.pkl', 'wb') as f:
    pickle.dump(ridge_model, f)

# Save the training columns to ensure order matches
with open('model_columns.pkl', 'wb') as f:
    pickle.dump(xtrain.columns.tolist(), f)